parseConfig:
  match:
    # 不要使用pod的label或者annotation进行匹配
    # 使用路径或者容器名称进行匹配
    matchField:
      - name: alllog
        key: tag
        matchRegex: ".+"
      - name: empdirlog
        key: logpath
        matchRegex: .*empty-dir.*
      - name: containerlog
        key: logpath
        matchRegex: .*log/containers.*

  parser:
    parseRegex:
      - name: getPodUid
        key: logpath
        preserve_key: true
        regex: ".*pods/?(?P<podUid>[a-z0-9](?:[-a-z0-9]*[a-z0-9]))?/volumes/.*"
      - name: getPodName
        key: logpath
        preserve_key: true
        regex: '([^.]+)?/(?P<podName>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?P<podNamespace>[^_]+)_(?P<container>.+)-(?P<dockerId>[a-z0-9]{64})\.log$'
    parseK8sUid:
      - name: getPodInfoByUid
        key: podUid
    parseK8sName:
      - name: getPodInfoByName
        key: podName
        namespaceKey: podNamespace
    parseJson:
      - name: externalLog
        key: log
        preserve_key: false
    parseTimer:
      - name: parseMySQLTime
        key: time
        formats:
        - format: 2006-01-02T15:04:05.000000+08:00
        - offset: 8
          format: 2006-01-02 15:04:05
      - name: parseMySQLAuditTime
        formats:
          - format: 2006-01-02T15:04:05Z
          - format: 2006-01-02T15:04:05 MST
        key: timestamp
      - name: parseTidbAuditTime
        key: time
        formats:
        - format: 2006/01/02 15:04:05.000 +08:00
      - name: parseGaussDBTime
        key: time
        formats:
        - format: 2006-01-02 15:04:05.000
    parseTruncated:
      - name: truncatedLog
        # 8k
        maxLength: 8192
filters:
  - name: emptydirGetUid
    matchType: matchAll
    matchers:
      - empdirlog
    parsers:
      - getPodUid
      - getPodInfoByUid
  - name: kuberLogGetInfo
    matchType: matchAll
    matchers:
      - containerlog
    parsers:
      - getPodName
      - getPodInfoByName
  # truncated parser必须放到最后，其他parser要在这个parser之前
  - name: truncated
    matchType: matchAll
    matchers:
      - alllog
    parsers:
      - truncatedLog
