---
# Source: dts-api-server/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dboperator
  namespace: dts
---
# Source: dts-api-server/templates/configmap.yaml
apiVersion: v1
data:
  timezone: |
    Asia/Shanghai
kind: ConfigMap
metadata:
  name: timezone
  namespace: dts
---
# Source: dts-api-server/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dts-admin
  annotations:
    rbac.authorization.k8s.io/auroupdate: "true"
  labels:
    kubernets.io/bootstrapping: "rbac-defaults"
rules:
- apiGroups:
    - '*'
  resources:
    - '*'
  verbs:
    - '*'
- nonResourceURLs:
    - '*'
  verbs:
    - '*'
---
# Source: dts-api-server/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dboperator-dts
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dts-admin
subjects:
  - kind: ServiceAccount
    name: dboperator
    namespace: dts
---
# Source: dts-api-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dts-api-server
  namespace: dts
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dts-api-server
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: grpc
      port: 3001
      targetPort: 3001
---
# Source: dts-api-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dts-api-server
  namespace: dts
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: dts-api-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: dts-api-server
      labels:
        app.kubernetes.io/name: dts-api-server
        qfusion/useIstio: "true"
        mgrds/run: "master"
    spec:
      serviceAccountName: dboperator
      terminationGracePeriodSeconds: 30
      affinity: 
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - dts-api-server
            topologyKey: kubernetes.io/hostname
      
      tolerations: 
        - effect: NoExecute
          key: qfusion/master
          operator: Exists
        - effect: NoExecute
          key: node-role.kubernetes.io/master
          operator: Exists
          tolerationSeconds: 60
      containers:
        - name: api
          image: k8smaster.qfusion.irds/irds/dbmotion:2310-hcs-oem
          imagePullPolicy: Always
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: DBMOTION_IMAGE
              value: k8smaster.qfusion.irds/irds/dbmotion:2310-hcs-oem
            - name: KAFKA_IMAGE
              value: k8smaster.qfusion.irds/irds/kafka:hcs-oem
            - name: DBMOTION_INIT_IMAGE
              value: k8smaster.qfusion.irds/irds/alpine:3.18.2
            - name: DBMOTION_WEB_ADDR
              value: http://dts-ingressgateway:80
            - name: DBMOTION_PUB_IP
              value: 127.0.0.1
            - name: DBMOTION_GORM_DEBUG
              value: "yes"
            - name: SERVER_MODE
              value: "PROXY"
            - name: K8S_NAMESPACE
              value: "dts"
            - name: NODE_SELECTOR_KEY
              value: "qfusion/node"
            - name: NODE_SELECTOR_VALUE
              value: ""
            - name: MASTER_TOLERATION
              value: "y"
            - name: MYSQL_HOST
              value: qfusion-cmdb0.qfusion
            - name: MYSQL_PORT
              value: "3306"
            - name: DBMOTION_SECURITY_ENABLE
              value: "y"
            - name: MYSQL_USER_NAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: cmdb0-root-suffix
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cmdb0-root-suffix
            - name: CPU_REQUEST
              value: 100m
            - name: CPU_LIMIT
              value: "4"
            - name: MEMORY_REQUEST
              value: 100Mi
            - name: MEMORY_LIMIT
              value: 8Gi
            - name: ELASTICSEARCH_URI
              value: http://elasticsearch-logging.dts:9200
            - name: PHOENIX_ENDPOINT
              value: http://phoenix.dts:9091/api/v2/phoenix
            - name: ELASTICSEARCH_IDX
              value: "qfrds-dbmotion.log*"
            - name: SAAS_MODE
              value: "HCS"
            - name: CMDB_URI
              value: $(MYSQL_USER_NAME):$(MYSQL_PASSWORD)@qfusion-cmdb0.qfusion:3306/webserver
            - name: MYSQL_URI
              value: $(MYSQL_USER_NAME):$(MYSQL_PASSWORD)@qfusion-cmdb0.qfusion:3306/dbmotion
            - name: ROOT_CA
              value: /etc/dbmotion-cert-ca.crt
            - name: CLIENT_CERT_FILE
              value: /etc/dbmotion-cert-dts-apiserver/tls.crt
            - name: CLIENT_KEY_FILE
              value: /etc/dbmotion-cert-dts-apiserver/tls.key
            - name: HTTP_MODE
              value: https
            - name: GIN_MODE
              value: release
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: log-volume
              mountPath: /dbmotion/log
            - name: dbmotion-cert-dts-apiserver
              mountPath: /etc/dbmotion-cert-dts-apiserver
            - name: dbmotion-cert-ca
              mountPath: /etc/dbmotion-cert-ca
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: grpc
              containerPort: 3001
              protocol: TCP
      volumes:
        - name: timezone
          configMap:
            name: timezone
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: log-volume
          emptyDir: { }
        - name: dbmotion-cert-ca
          secret:
            secretName: dbmotion-cert-ca
        - name: dbmotion-cert-dts-apiserver
          secret:
            secretName: dbmotion-cert-dts-apiserver
