apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: grafana
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  template:
    metadata:
      annotations:
        grafana-version: '1.0'
      name: grafana
      labels:
        app.kubernetes.io/name: grafana
        qfusion/useIstio: "true"
        mgrds/run: "master"
    spec:
      containers:
        - name: grafana
          image: {{ .Values.global.registry }}/{{.Values.global.repository}}/{{ .Values.global.imageName }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsUser: 0
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.adminPassword }}
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_SECURITY_ALLOW_EMBEDDING
              value: "true"
          ports:
            - name: grafana
              containerPort: 3000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: dashboards.yaml
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards/
            - name: grafana-provisioning
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            {{ if .Values.enableHttps }}
            - name: grafana-secret
              mountPath: /grafana/ssl/
            {{- end }}
      volumes:
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
        - name: grafana-provisioning
          configMap:
            name: grafana-provisioning
        {{ if .Values.enableHttps }}
        - name: grafana-secret
          secret:
            secretName: grafana-secret
        {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}