apiVersion: v1
kind: Secret
metadata:
  name: grafana-password
  namespace: {{.Release.Namespace}}
data:
  GF_SECURITY_ADMIN_PASSWORD: Q2xqc2xybDA2MjA=
  GF_SECURITY_SECRET_KEY: U1cyWWN3VEliOXpwT09ob1BzTW0=
