apiVersion: v1
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.qfusion.svc:15012
      proxyMetadata:
        ISTIO_AGENT_DUAL_STACK: "true"
      tracing: {}
    discoverySelectors:
    - matchLabels:
        qf-istio-discovery: enabled
    enablePrometheusMerge: true
    rootNamespace: qfusion
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
metadata:
  labels:
    install.operator.istio.io/owning-resource: unknown
    installer.woqutech.com/managed-by: qfusion-installer-operator
    installer.woqutech.com/package: qfusion-istio
    istio.io/rev: default
    operator.istio.io/component: Pilot
    release: istio
  name: istio
  namespace: dts
---
apiVersion: v1
data:
  root-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIC/DCCAeSgAwIBAgIQRE8ftEPOEAPErgOaSp7vHDANBgkqhkiG9w0BAQsFADAY
    MRYwFAYDVQQKEw1jbHVzdGVyLmxvY2FsMB4XDTIzMTIwNDA1NTg0MVoXDTMzMTIw
    MTA1NTg0MVowGDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBAKi/auDCKQIsE/sUJR3JeFieonlBQv/ZFpFgk7f/
    x4F0gcgI2Qd+LS3M18yAfhmR32hkTXK0M8JO26fYV1lrhwYxxFMOPpjSqmJgIh6q
    ZgTrF/7dW1mTNCndIRC/HsbCn8djxvlypXIfuAnla9cHDBSq182TLUl+Z4/ypVSt
    fQ6BpcODNDcU4uSmVmeAsgjn7EsGiXqgklIhvPGf3nPkAq8r5hC9xmVxvD5e7XuS
    QuHe77IlrKlLpwpoPwuI0/Vt5FBabjYyqNcQo6XQT2whfk1IqeRQ3PQ8ebjt9m3o
    c0fBypKV8GxTkcdPK68LTFGngZ4BDW0u987cmDvRW6f3bvsCAwEAAaNCMEAwDgYD
    VR0PAQH/BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFFeByrOl87P9
    tfX+uBaJrrRWhKd0MA0GCSqGSIb3DQEBCwUAA4IBAQCVKrTGQaix+t6JSkg3y6QU
    xXcffLkuIjgU559e8qLTt0vTJ18ziGhcFVeK/p8ScAAmGU1UZHz+9PDb4TrtRRaz
    k5iVmjzZMbCfTcU4M50M17PSSHFB/EZ0TIzFPq3544VLMWzVQWPqVE/7lmoyCEKE
    M4xCEX89T0HO0hbaR/RV8Z3zjLSXZzFcjBuHyQBr+Osqzag8fCT4D8+DAAZiIg5X
    c/W3MJ/AYjAZuG+v4z7dJXJUXE12x44ReAAV3YLnKT1Bonzt5DOlpAO2OjuvQbj4
    +Lq/jm3NSKYsAGAsGpb3dtlHOElohdlZzZ00+37Rc4en3boPXis+bcJ731r2ZIeZ
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  labels:
    istio.io/config: "true"
  name: istio-ca-root-cert
  namespace: dts