apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  generation: 1
  labels:
    kiali_wizard: web-Gateway
  name: webserver
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: dts-ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http-web
      number: 80
      protocol: HTTP
