kind: Service
apiVersion: v1
metadata:
  name: monitor-headless
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: monitor
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: monitor
  ports:
    - name: web
      protocol: TCP
      port: 9090
      targetPort: web
    - name: grpc
      port: 10901
      targetPort: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: monitor
  labels:
    name: monitor
    namespace: {{ .Release.Namespace }}
    kubernetes.io/cluster-service: 'true'
spec:
  ports:
    - name: monitor
      {{- if and .Values.nodeExporter.nodePort .Values.nodeExporter.monitor }}
      nodePort: {{ $.Values.nodeExporter.monitor }}
      {{- end }}
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/name: monitor
  sessionAffinity: None
  {{- with .Values.nodeExporter.nodePort }}
  type: NodePort
  {{- end }}
