apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: monitor
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: monitor
spec:
  serviceName: monitor-headless
  podManagementPolicy: Parallel
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: monitor
  template:
    metadata:
      name: monitor
      labels:
        app.kubernetes.io/name: monitor
        qfusion/useIstio: "true"
        mgrds/run: "master"
    spec:
      serviceAccountName: monitor
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: dts-monitor-conf
          image: {{.Values.conf.image.registry}}/{{.Values.conf.image.repository}}/{{.Values.conf.image.name}}:{{ .Values.conf.image.tag }}
          command:
            - sh
            - -c
            - |
              cd /dts-monitor
              cp -p * /dts-conf/
              chmod 777 /dts-data
          volumeMounts:
            - name: monitor-conf
              mountPath: /dts-monitor
            - name: shared-conf
              mountPath: /dts-conf
            - name: dts-data
              mountPath: /dts-data
      containers:
        - name: prometheus
          image: {{.Values.prometheus.image.registry}}/{{.Values.prometheus.image.repository}}/{{.Values.prometheus.image.name}}:{{ .Values.prometheus.image.tag }}
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.enable-lifecycle
            - --storage.tsdb.retention=180d
            - --storage.tsdb.path=/prometheus/data
            - --storage.tsdb.retention.time={{ .Values.prometheus.storage.retentionTime }}
            - --web.route-prefix=/
            - --storage.tsdb.no-lockfile
            - --storage.tsdb.min-block-duration={{ .Values.prometheus.storage.minBlockDuration }}
            - --storage.tsdb.max-block-duration={{ .Values.prometheus.storage.maxBlockDuration }}
            - --log.level=debug
          ports:
            - name: web
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /-/healthy
              port: web
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 120
            httpGet:
              path: /-/ready
              port: web
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          volumeMounts:
            - name: monitor-conf
              mountPath: /etc/prometheus
            - name: dts-data
              mountPath: /prometheus/data
            - name: shared-conf
              mountPath: /dts-conf
            - name: timezone
              mountPath: /etc/timezone
            - name: localtime
              mountPath: /etc/localtime
      volumes:
        - name: monitor-conf
          configMap:
            defaultMode: 432
            name: monitor-conf
        - name: shared-conf
          emptyDir: { }
        - name: tmpl-volume
          emptyDir: { }
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: dts-data
          hostPath:
            path: /opt/qfusion/dts-monitor
      {{- with .Values.affinity }}
      affinity: {{toYaml .| nindent 8}}
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}