apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: fluent-bit-read-{{.Release.Namespace}}
rules:
    - apiGroups: [""]
      resources:
          - namespaces
          - pods
      verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: fluent-bit-read-{{.Release.Namespace}}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: fluent-bit-read-{{.Release.Namespace}}
subjects:
    - kind: ServiceAccount
      name: fluent-bit
      namespace: {{.Release.Namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: fluent-bit
    namespace: {{.Release.Namespace}}
{{- with .Values.global}}
{{- with .imagePullSecret }}
imagePullSecrets:
  - name: {{ . }}
{{- end}}
{{- end}}
