# Default values for monitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nodeExporter:
  nodePort: true
  prometheus: 32005

conf:
  image:
    registry: k8smaster.qfusion.irds
    repository: irds
    name: alpine
    tag: 3.18.2

database:
  address: "qfusion-cmdb0.qfusion"
  port: "3306"
  secret: qfusion-cmdb0-root-suffix
  name: dts_phoenix

prometheus:
  image:
    registry: k8smaster.qfusion.irds
    repository: irds
    name: prometheus
    pullPolicy: IfNotPresent
    tag: v2.47.0
  storage:
    retentionTime: 10d
    minBlockDuration: 2h
    maxBlockDuration: 2h
  pvcSize: 200Gi

resources: { }
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector:
  qfusion/master: "true"

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: prometheus
        topologyKey: kubernetes.io/hostname
