{
 "title": "full migration",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "task_id", "label": "task_id", "query": { "query": "label_values(task_id)" } }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "rows per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(dts_data_row_count{event_type=\"read\", task_id=\"$task_id\"}[5m])",
     "legendFormat": "read source db"
    },
    {
     "expr": "rate(dts_data_row_count{event_type=\"write\", task_id=\"$task_id\"}[5m])",
     "legendFormat": "write target db"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "bytes per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(dts_data_bytes{event_type=\"read\", task_id=\"$task_id\"}[5m])",
     "legendFormat": "read source db"
    },
    {
     "expr": "rate(dts_data_bytes{event_type=\"write\", task_id=\"$task_id\"}[5m])",
     "legendFormat": "write target db"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "description": "transactions per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(dts_data_transaction_count{event_type=\"read\", task_id=\"$task_id\"}[5m])",
     "legendFormat": "read source db"
    },
    {
     "expr": "rate(dts_data_transaction_count{event_type=\"write\", task_id=\"$task_id\"}[5m])",
     "legendFormat": "write target db"
    }
   ]
  },
  {
   "title": "Database Response Time",
   "type": "timeseries",
   "description": "database response time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dts_data_sql_response_time{event_type=\"read\", task_id=\"$task_id\"}",
     "legendFormat": "source db"
    },
    {
     "expr": "dts_data_sql_response_time{event_type=\"write\", task_id=\"$task_id\"}",
     "legendFormat": "target db"
    }
   ]
  },
  {
   "title": "Queued Rows",
   "type": "timeseries",
   "description": "rows in queue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max(dts_data_row_count{event_type=\"read\", task_id=\"$task_id\"}) - min(dts_data_row_count{event_type=\"write\", task_id=\"$task_id\"})",
     "legendFormat": "rows in queue"
    }
   ]
  },
  {
   "title": "Network Delay",
   "type": "timeseries",
   "description": "network delay",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dts_network_delay{end_type=\"source\", task_id=\"$task_id\"}",
     "legendFormat": "source db"
    },
    {
     "expr": "dts_network_delay{end_type=\"target\", task_id=\"$task_id\"}",
     "legendFormat": "target db"
    }
   ]
  }
 ]
}