apiVersion: apps/v1
kind: Deployment
metadata:
  name: dts-api-server
  namespace: {{.Release.Namespace}}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: dts-api-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: dts-api-server
      labels:
        app.kubernetes.io/name: dts-api-server
        qfusion/useIstio: "true"
    spec:
      serviceAccountName: dboperator
      terminationGracePeriodSeconds: 30
      {{- with .Values.api.affinity }}
      affinity: {{toYaml .| nindent 8}}
      {{end}}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: {{ .Values.global.registry }}/{{ .Values.global.repository }}/{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: DBMOTION_IMAGE
              value: {{ .Values.global.registry }}/{{ .Values.global.repository }}/{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}
            - name: DBMOTION_BINLOG_CACHE_ADDR
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: DBMOTION_INIT_IMAGE
              value: {{ .Values.global.registry }}/{{ .Values.global.repository }}/{{ .Values.api.initImage.name }}:{{ .Values.api.initImage.tag }}
            - name: DBMOTION_WEB_ADDR
              value: {{ .Values.dbmotion.webAddr }}
            - name: DBMOTION_PUB_IP
              value: {{ .Values.dbmotion.public.ip }}
            - name: DBMOTION_GORM_DEBUG
              value: "yes"
            - name: SERVER_MODE
              value: "SAAS"
            - name: K8S_NAMESPACE
              value: "dts"
            - name: NODE_SELECTOR_KEY
              value: "qfusion/node"
            - name: NODE_SELECTOR_VALUE
              value: ""
            - name: MASTER_TOLERATION
              value: "y"
            - name: MYSQL_HOST
              value: {{  .Values.cmdbAddr }}
            - name: MYSQL_PORT
              value: "{{  .Values.cmdbPort }}"
            - name: DBMOTION_SECURITY_ENABLE
              value: "y"
            - name: MYSQL_USER_NAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: cmdb0-root-suffix
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cmdb0-root-suffix
            - name: CPU_REQUEST
              value: 100m
            - name: CPU_LIMIT
              value: "4"
            - name: MEMORY_REQUEST
              value: 100Mi
            - name: MEMORY_LIMIT
              value: 8Gi
            - name: ELASTICSEARCH_URI
              value: {{ .Values.es.url }}
            - name: PHOENIX_ENDPOINT
              value: {{ .Values.phoenix.endpoint }}
            - name: ELASTICSEARCH_IDX
              value: "qfrds-dbmotion.log*"
            - name: SAAS_MODE
              value: "SAAS"
            - name: CMDB_URI
              value: {{  .Values.cmdbUri }}
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: log-volume
              mountPath: /dbmotion/log
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: grpc
              containerPort: 3001
              protocol: TCP
        - env:
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_LOG_DIRS
              value: /kafka/kf
            - name: ZOOKEEPER_DATA__DIR
              value: /kafka/zk
          image: {{ .Values.global.registry }}/{{ .Values.global.repository }}/{{ .Values.api.kafkaImage.name }}:{{ .Values.api.kafkaImage.tag }}
          imagePullPolicy: Always
          name: kafka
          ports:
            - containerPort: 9092
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /kafka
              name: data
            - mountPath: /etc/timezone
              name: timezone
              subPath: timezone
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - name: timezone
          configMap:
            name: timezone
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: log-volume
          emptyDir: { }
        - name: data
          persistentVolumeClaim:
            claimName: data