apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: {{.Release.Namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: csi-localpv
  volumeMode: Filesystem
