apiVersion: v1
kind: Service
metadata:
  name: dts-api-server
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dts-api-server
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: grpc
      port: 3001
      targetPort: 3001