apiVersion: apps/v1
kind: Deployment
metadata:
  name: dts-ui
  namespace: {{.Release.Namespace}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: dts-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dts-ui
        qfusion/useIstio: "true"
        mgrds/run: "master"
    spec:
      {{- with .Values.affinity }}
      affinity: {{toYaml .| nindent 8}}
      {{end}}
      containers:
        - name: ui
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          env:
            - name: TMOUT
              value: "{{ .Values.tmout }}"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: web-nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
            type: ""
        - name: web-nginx-conf
          configMap:
            name: web-nginx-conf