apiVersion: v1
kind: Service
metadata:
  name: dts-ui
  namespace: {{.Release.Namespace}}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: dts-ui
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30000