---
# Source: fluentbit/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
    name: fluent-bit
    namespace: dts
---
# Source: fluentbit/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
    name: fluentbit
    namespace: dts
data:
  filter_cgolib.conf: |-
    [FILTER]
        Name  go
        Match  *
        golib_so /fluent-bit/lib/cgolib.so
        lib_args -logtostderr=true
        # modules that you must init, split by ','
        init_modules k8s
        # for k8s init
        # kube_config /fluent-bit/etc/kube-config   // in cluster , no need config
        # filters in cgolib you want to use. key must begin with 'filters'
        filters_1  parseFilter
        parse_config_file  /fluent-bit/etc/filter_cgolib.yaml
  
    [FILTER]
        name   grep
        match  containerlog
        regex  log .+
  filter_cgolib.yaml: |
    parseConfig:
      match:
        # 不要使用pod的label或者annotation进行匹配
        # 使用路径或者容器名称进行匹配
        matchField:
          - name: alllog
            key: tag
            matchRegex: ".+"
          - name: empdirlog
            key: logpath
            matchRegex: .*empty-dir.*
          - name: containerlog
            key: logpath
            matchRegex: .*log/containers.*
  
      parser:
        parseRegex:
          - name: getPodUid
            key: logpath
            preserve_key: true
            regex: ".*pods/?(?P<podUid>[a-z0-9](?:[-a-z0-9]*[a-z0-9]))?/volumes/.*"
          - name: getPodName
            key: logpath
            preserve_key: true
            regex: '([^.]+)?/(?P<podName>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?P<podNamespace>[^_]+)_(?P<container>.+)-(?P<dockerId>[a-z0-9]{64})\.log$'
        parseK8sUid:
          - name: getPodInfoByUid
            key: podUid
        parseK8sName:
          - name: getPodInfoByName
            key: podName
            namespaceKey: podNamespace
        parseJson:
          - name: externalLog
            key: log
            preserve_key: false
        parseTimer:
          - name: parseMySQLTime
            key: time
            formats:
            - format: 2006-01-02T15:04:05.000000+08:00
            - offset: 8
              format: 2006-01-02 15:04:05
          - name: parseMySQLAuditTime
            formats:
              - format: 2006-01-02T15:04:05Z
              - format: 2006-01-02T15:04:05 MST
            key: timestamp
          - name: parseTidbAuditTime
            key: time
            formats:
            - format: 2006/01/02 15:04:05.000 +08:00
          - name: parseGaussDBTime
            key: time
            formats:
            - format: 2006-01-02 15:04:05.000
        parseTruncated:
          - name: truncatedLog
            # 8k
            maxLength: 8192
    filters:
      - name: emptydirGetUid
        matchType: matchAll
        matchers:
          - empdirlog
        parsers:
          - getPodUid
          - getPodInfoByUid
      - name: kuberLogGetInfo
        matchType: matchAll
        matchers:
          - containerlog
        parsers:
          - getPodName
          - getPodInfoByName
      # truncated parser必须放到最后，其他parser要在这个parser之前
      - name: truncated
        matchType: matchAll
        matchers:
          - alllog
        parsers:
          - truncatedLog
  fliter_global.conf: |
    [FILTER]
        # 过滤空行
        Name        grep
        Match       *.log
        Exclude     \s+
  
    [FILTER]
        # 排除掉分隔符，标题型日志
        Name    grep
        Match   *
        Exclude ^(\*|=)+.*(\*|=)+$
  fluent-bit-db.conf: |
    [SERVICE]
        Flush         1
        # Log_Level     Trace
        Log_Level     info
        Daemon        off
        Parsers_File  parsers_parser.conf
        Parsers_File  parsers_db.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        storage.path              ${FLUENT_FILESYSTEM_PATH}
        storage.sync              normal
        storage.checksum          off
        storage.backlog.mem_limit 100M
        scheduler.base   3
        scheduler.cap    600
  
    @INCLUDE input_db.conf
    @INCLUDE filter_*.conf
    @INCLUDE output_*.conf
  fluent-bit-k8s.conf: |
    [SERVICE]
        Flush         1
        # Log_Level     Trace
        Log_Level     info
        Daemon        off
        Parsers_File  parsers_parser.conf
        Parsers_File  parsers_db.conf
        storage.path              ${FLUENT_FILESYSTEM_PATH}
        storage.sync              normal
        storage.checksum          off
        storage.backlog.mem_limit 100M
        scheduler.base   3
        scheduler.cap    600
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
  
    @INCLUDE input_k8s.conf
    @INCLUDE filter_*.conf
    @INCLUDE output_*.conf
  input_db.conf: |
    [INPUT]
        Name              tail
        Alias             es_log
        Tag               dbmotion.log
        Path              /var/lib/kubelet/pods/*/volumes/kubernetes.io~empty-dir/log-volume/*/dbmotion.log
        Multiline         On
        Multiline_Flush   5
        Parser_Firstline  dbmotion_parser
        Path_Key          logpath
        DB                /var/log/flb_dbmotion.db
        Mem_Buf_Limit     300MB
        Skip_Long_Lines   On
        Buffer_Max_Size   200k
        Buffer_Chunk_Size 100k
        Refresh_Interval  3
  input_k8s.conf: |
    [INPUT]
        Name              tail
        Tag               containerlog
        Alias             container_log
        Path              /var/log/containers/*.log
        Exclude_Path      /var/log/containers/*fluent-bit*.log,/var/log/containers/*kubevirt*.log
        Parser            ${FLUENT_CONTAINER_LOG_PARSER}
        Path_Key          logpath
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     500MB
        Buffer_Max_Size   800k
        storage.type  filesystem
        Buffer_Chunk_Size 700k
        Skip_Long_Lines   On
        Refresh_Interval  10
  limits.conf: |
    * soft nofile 65534
    * hard nofile 65534
    root soft nofile 65534
    root hard nofile 65534
  output_es.conf: |+
    [OUTPUT]
        Name            es
        Alias           es_log
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            9200
        Logstash_Format On
        Logstash_Prefix log
        Include_Tag_Key Off
        Retry_Limit     False
        Generate_ID     on
        Trace_Error     on
        storage.total_limit_size  ${FLUENT_FILESYSTEM_LIMIT_SIZE}
        Write_Operation upsert
        Logstash_Prefix_Key tag
  
  parsers_db.conf: |-
    [PARSER]
        Name        dbmotion_parser
        Format      json
  parsers_parser.conf: |+
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   escaped    log
  
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Keep   On
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
  
    [PARSER]
        Name        time_parser
        Format      regex
        Regex       ^(?<time>\d{4}-\d{2}-\d{2}[\S| ]\d{2}:\d{2}:\d{2}\.[\d|+|:]*)(?<log>(.|\n)*)
  
    [PARSER]
        Name        json_parser
        Format      json
---
# Source: fluentbit/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: fluent-bit-read-dts
rules:
    - apiGroups: [""]
      resources:
          - namespaces
          - pods
      verbs: ["get", "list", "watch"]
---
# Source: fluentbit/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: fluent-bit-read-dts
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: fluent-bit-read-dts
subjects:
    - kind: ServiceAccount
      name: fluent-bit
      namespace: dts
---
# Source: fluentbit/templates/daemonset.yaml
# 采集数据库相关的日志
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit-database
  namespace: dts
  labels:
    helm.sh/chart: fluentbit-0.1.0
    app.kubernetes.io/name: fluentbit
    app.kubernetes.io/instance: fluentbit
    app.kubernetes.io/version: "1.4.5"
    app.kubernetes.io/managed-by: Helm
    type: database
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluentbit
      app.kubernetes.io/instance: fluentbit
      type: database
  template:
    metadata:
      labels:
        helm.sh/chart: fluentbit-0.1.0
        app.kubernetes.io/name: fluentbit
        app.kubernetes.io/instance: fluentbit
        app.kubernetes.io/version: "1.4.5"
        app.kubernetes.io/managed-by: Helm
        type: database
    spec:
      tolerations: 
        - effect: NoSchedule
          key: qfusion/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      containers:
        - name: fluent-bit
          image: k8smaster.qfusion.irds/irds/fluent-bit:2.0.9.1-hcs-oem
          imagePullPolicy: Always
          ports:
            - containerPort: 2020
          command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit-db.conf"]
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch-logging.dts.svc.cluster.local"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_FILESYSTEM_LIMIT_SIZE
              value: 10G
            - name: FLUENT_FILESYSTEM_PATH
              value: /flb-storage/database
            - name: FLUENT_CONTAINER_LOG_PARSER
              value: docker
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibpodcontainers
              mountPath: /var/lib/kubelet/pods
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
            - name: containers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: limit
              mountPath: /etc/security/limits.conf
              subPath: limits
            - mountPath: /etc/localtime
              name: localtime
            - mountPath: /flb-storage
              name: storage
      terminationGracePeriodSeconds: 10
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: storage
          hostPath:
            path: /opt/dts/flb-storage
        - name: varlibpodcontainers
          hostPath:
            path: /var/lib/kubelet/pods
        - name: containers
          hostPath:
              path: /var/lib/docker/containers
        - name: fluent-bit-config
          configMap:
            name: fluentbit
        - name: limit
          configMap:
            name: fluentbit
            items:
              - key: limits.conf
                path: limits
        - hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
          name: localtime
      serviceAccountName: fluent-bit
---
# Source: fluentbit/templates/daemonset.yaml
# 采集k8s容器相关的日志
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit-k8s
  namespace: dts
  labels:
    helm.sh/chart: fluentbit-0.1.0
    app.kubernetes.io/name: fluentbit
    app.kubernetes.io/instance: fluentbit
    app.kubernetes.io/version: "1.4.5"
    app.kubernetes.io/managed-by: Helm
    type: k8s
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluentbit
      app.kubernetes.io/instance: fluentbit
      type: k8s
  template:
    metadata:
      labels:
        helm.sh/chart: fluentbit-0.1.0
        app.kubernetes.io/name: fluentbit
        app.kubernetes.io/instance: fluentbit
        app.kubernetes.io/version: "1.4.5"
        app.kubernetes.io/managed-by: Helm
        type: k8s
    spec:
      tolerations: 
        - effect: NoSchedule
          key: qfusion/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      containers:
        - name: fluent-bit
          image: k8smaster.qfusion.irds/irds/fluent-bit:2.0.9.1-hcs-oem
          imagePullPolicy: Always
          ports:
            - containerPort: 2020
          command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit-k8s.conf"]
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch-logging.dts.svc.cluster.local"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_FILESYSTEM_LIMIT_SIZE
              value: 10G
            - name: FLUENT_FILESYSTEM_PATH
              value: /flb-storage/k8s
            - name: FLUENT_CONTAINER_LOG_PARSER
              value: docker
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
            - name: limit
              mountPath: /etc/security/limits.conf
              subPath: limits
            - mountPath: /etc/localtime
              name: localtime
            - mountPath: /flb-storage
              name: storage
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluent-bit-config
          configMap:
            name: fluentbit
        - name: limit
          configMap:
            name: fluentbit
            items:
              - key: limits.conf
                path: limits
        - hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
          name: localtime
        - name: storage
          hostPath:
            path: /opt/dts/flb-storage
      serviceAccountName: fluent-bit
